### ISSUE TITLE
iOS 17.0 でクラッシュする

### ISSUE THREAD

**Issue by sassa7777** [cpprefjp/site#1457]
iOS17.0 Webkit 605.1.15の環境でサイトを開くと繰り返し問題が発生しました。と表示され、開くことができません。

**Comment by faithandbrave** [comment]
報告ありがとうございます。
私はiOS 18.5の環境ですが、Safari、Chromeで問題なくページが表示されました。

以前まではページを開けていましたか？
ここ数ヶ月はJavaScriptの依存ライブラリアップデートもとくにしていないので、生成されるHTMLとしては安定してるはずではあるのですが…。

ほかの方で、同様の問題が発生してる人がいたら教えてください。

**Comment by sassa7777** [comment]
少し前(数ヶ月ぐらい？)は開けていましたが、ここしばらく開けていません。

**Comment by sassa7777** [comment]
どちらもだめでした。

**Comment by faithandbrave** [comment]
Claude Codeに聞いてみました。

```
⏺ iOS17 Safariエラーの原因分析結果

  以下の問題が「A problem repeatedly occurred」エラーを引き起こしている可能性があります：

  主な問題点

  1. 無限ループ・メモリリーク - kunai/js/kunai/yata.js:209-230
    - autoRefreshメソッドでsetIntervalが適切にクリアされない可能性
  2. 大量のDOM操作 - kunai/js/kunai/treeview.js:362-403, 57-59
    - Promise.allで大量の要素を一度に生成しメモリ不足を引き起こす可能性
  3. CSS問題
    - kunai/css/layout.css:120: -webkit-overflow-scrolling: touchはiOS Safariで描画問題を起こしやすい
    - kunai/css/sidebar.css:211: position: stickyがiOS Safariで正しく動作しない場合がある
  4. file://プロトコル処理 - kunai/js/kunai.js:155-167
    - iOS Safariのセキュリティ制限により予期しない動作の可能性
  5. MathJax v3 - cpprefjp/templates/content.html:133
    - 大量の数式レンダリング時にメモリ問題を引き起こす可能性

  特に大量のDOM操作とメモリ管理の問題が、モバイルデバイスでクラッシュを引き起こしている可能性が高いです。
```

**Comment by faithandbrave** [comment]
MathJaxの指摘はおそらく関係ないので、そのままです (そんなに大量の数式は使ってないですし、使ってないページではMathJaxはオフになってるので)

**Comment by yohhoy** [comment]
Windows 10/Chrome, Android/Chromeでも表示に問題ないですね。
（なんとなくサイト表示が軽くなった？単にプラシーボ効果かもしれません。）

ページは常に増えつづけますから、kunai/js/kunai/treeview.js 処理がどんどん重くなったせいなのかもですね。

**Comment by faithandbrave** [comment]
ソースではなく、コンソールタブの内容を貼り付けていただけますでしょうか。
また、ここまでに解決方法として提示されたものを、この段階でなにを実施した結果としてこうなっているのかを明記してください (Safariの設定、キャッシュクリアなど)。

**Comment by sassa7777** [comment]
vector, shared_ptrともに他と同じでした。使っているデバイスはiPhone SE 第2世代です

**Comment by faithandbrave** [comment]
iPhone SE 第2世代ではRAMが少ないために、CSSのbox-shadowなどでGPUメモリ使用量を多用するとクラッシュすることがあるそうでした。
またClaude Codeに聞きながら修正をしてデプロイしてみました。

```
この解決方法を元に、以下を修正
https://stackoverflow.com/questions/76127296/debugging-a-ios-safari-crash-a-problem-repeatedly-occurred

1. 大きな要素のbox-shadow無効化
    - kunai/css/kunai/site/layout.css:
      メインコンテナとヘッダーの大きなbox-shadowを無効化
    - GPUメモリを大量に消費する原因となる大きな要素への影の適用を削除
2. tooltipの最適化
    - kunai/css/kunai/site/tooltip.css:
        - box-shadowを削除し、代わりにborderで視覚効果を維持
    - 複雑なtransitionを簡略化（opacity以外のz-index transitionを削除）
3. サイドバーの最適化
    - kunai/css/kunai/site/sidebar.css: inset box-shadowをborderに置き換え

効果

これらの修正により、以下の効果が期待できます：

- GPUメモリ使用量の大幅削減 - 特に大きな要素へのbox-shadowとopacity/transitionの組み合わせを削除
- コンポジットレイヤー数の削減 - 不要なGPUレイヤーの生成を抑制
- iOS Safariでのパフォーマンス向上
- メモリ使用量の削減によりクラッシュを防止

Stack Overflowの投稿と同様に、視覚的な影響を最小限に抑えながら、GPUメモリ使用量を大幅に削減できました。
```

こちらもブラウザのキャッシュをして試してみてください。
キャッシュクリアの方法は、以下に記載があります。

- [iPhone、iPad、iPod touch で Safari から閲覧履歴、キャッシュ、Cookie を消去する - Apple サポート (日本)](https://support.apple.com/ja-jp/105082)

> Cookie とキャッシュを消去し、履歴は残す
> 「設定」>「アプリ」>「Safari」>「詳細」>「Web サイトデータ」の順に選択します。
>
> 「全 Web サイトデータを削除」をタップします。

**Comment by planaria** [comment]
iPadOS 16.6 (20G75) でも発生しました。
ローカルでサーバーを立てて再現できたのでこちらで最小コードを見つけてみます。
<img width="4080" height="3060" alt="Image" src="https://github.com/user-attachments/assets/442d5459-954d-4f0a-9592-34e029d653a0" />

**Comment by faithandbrave** [comment]
ありがとうございます！大変助かります！

OS再起動で直る可能性がある、という情報をいただきました。
クラッシュする現象が起きた方は、そちらも試していただきたいです。

**Comment by planaria** [comment]
kunai-stage-3.css を削っていくとエラーにならなくなるのですが、
特定の行を削るとエラーにならなくなるというより、
量が少なくなるとエラーにならなくなる、という動作に見えます。

以下のような複雑な行が多く含まれているので、こういった行が一定数を超えるとエラーになるのかもしれません。

```css
`:is(:is(:is(:is(.kunai-sidebar>.tree.v2) .kunai-branch)>ul.branch)>li):not(.top):not(.headers):not(.header):not(.category):not(.module):not(.lang):not(.classes):not(.members):not(.class):not(.article):hover {
```

**Comment by planaria** [comment]
ギリギリまで削った kunai-stage-3.css を添付しました。
[kunai-stage-3.zip](https://github.com/user-attachments/files/21733718/kunai-stage-3.zip)

このファイルを使うとエラーになるのですが、
このファイルから先頭のルールを削除するとエラーにならなくなり、
このファイルから末尾のルールを削除してもエラーにならなくなります。

**Comment by faithandbrave** [comment]
Claude Codeに聞いたところ、以下の設定を推奨されました。

```
iOS Safariのクラッシュ対策として、以下の設定変更を推奨します：

  postcss.config.js:50 でcssnanoオプションを調整:
  cssnano: {
    preset: ['default', {
      // 複雑な最適化を無効化
      calc: false,
      zindex: false,
      mergeRules: false,
      minifyGradients: false,
      // セレクタの深さを制限
      minifySelectors: false,
      // 既存設定を維持
      autoprefixer: false,
      reduceIdents: false
    }]
  }
```

これでローカルで動作確認し、問題なさそうであればデプロイしてみます

**Comment by planaria** [comment]
こちらで試してみましたが同じエラーが出ますね。
CSS の複雑さもそんなに変わっていないようです。

一例:
```css
:is(:is(:is(:is(.kunai-sidebar > .tree.v2) .kunai-branch) > ul.branch) > li):not(.top):not(.headers):not(.header):not(.category):not(.module):not(.lang):not(.classes):not(.members):not(.class):not(.article):hover {
    background-color: rgb(from #f0f0fd r g b/.9)
}
```

**Comment by planaria** [comment]
まだエラーが発生しますね...
深さの問題ではなかったのかもしれません。

**Comment by faithandbrave** [comment]
ChatGPTに聞いてみました。
hslのネストをやめればよさそうですね。

```
結論から言うと、これは **CSS Color 5「相対色指定（relative color syntax）」の実装バグ**が原因で起きるクラッシュです。
とくに **`hsl(from …)` の “from に相対色をさらにネスト”** し、かつ **チャンネル値に `calc()`（`s` などのチャンネル識別子を含む）** を使ったときに、WebKit の色計算フェーズが破綻します。

あなたの例で落ちる理由の芯はここです：

```css
/* 外側の hsl(from ...) の参照元が、さらに内側の hsl(from ...) になっている（相対色のネスト） */
.test {
  color: hsl(
    from hsl(from color-mix(in srgb, #2a6496, white 15%) h calc(s + 10%) l)
    h calc(s - 20%) l
  );
}
```

* `hsl(from A …)` の **A が相対色（= さらに `hsl(from …)`）** という **相対色の二段ネスト**
* その **内外の両方で `calc(s ± …%)` のようにチャンネル演算** をしている
* これが **WebKit の相対色解決（チャンネル展開）で循環的・未定義状態を誘発** し、クラッシュ（多くは無限再帰 or 不正参照）に至る挙動

一方、片方をコメントアウトすると落ちないのは、**相対色のネスト + `calc()` の組み合わせ** が消えるためです。
同じセレクタが2つあること自体（カスケード）は原因ではありません。

---

## 再現最小化（考え方）

以下のどれかを外すとクラッシュが止まりやすいはずです。

1. **相対色のネストをやめる**

```css
:root { --base: color-mix(in srgb, #2a6496, white 15%); }
.test {
  /* 参照元は相対色ではなく “普通の color” or 変数にする */
  color: hsl(from var(--base) h calc(s + 10%) l);
}
```

2. **チャンネルでの calc をやめる／一段に集約**

```css
:root {
  --base: color-mix(in srgb, #2a6496, white 15%);
  /* 先に一度だけ相対色＋calc を解決して変数に格納 */
  --base-tuned: hsl(from var(--base) h calc(s + 10%) l);
}
.test { color: var(--base-tuned); }
```

3. **`hsl(from …)` を1回に限定し、ネストを解消**

```css
:root {
  --mix: color-mix(in srgb, #2a6496, white 15%);
}
.test {
  /* 外側だけ relative、内側は absolute に寄せる */
  color: hsl(from var(--mix) h calc(s + 10%) l);
  /* もう1本の .test ルールは削除 or 同じ変数を使い回す */
}
```

4. **`calc()` を数値化してから渡す**（CSS変数で前計算）

---

## 実務的な回避ガイド

* **相対色の“入れ子”は避ける**（`hsl(from (hsl(from …)))` のような形をやめる）
* **チャンネル演算は1段で完結**（`calc()` を多段にしない、内外で重ねない）
* **カスタムプロパティに集約**して、`hsl(from var(--color) …)` を一か所だけにする
* 不特定端末向けなら `@supports (color: color-mix(in srgb, black, white))` でガードし、フォールバック色を用意

---

## メモ

* これは仕様上は合法な書き方ですが、**iOS 16 期の WebKit の相対色実装が未成熟**で、ネスト + `calc()` の組み合わせで落ちます。
* 端末／小数バージョンで挙動が異なることもあるため、可能なら **最新版（iOS 17 以降）で再検証**を。
* 最小再現が取れているので、WebKit Bugzilla へ「Relative color nested with channel calc causes crash」のように報告すると修正が通りやすいです。

必要なら、あなたのスタイル全体を安全に書き換えた **互換版CSS（相対色のネスト回避 + 同等見た目）** をこちらで作ります。

```
